ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 500
  ReadTimeout: 1500
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/