spring:
  application:
    name: sso-server
ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 500
  ReadTimeout: 1500
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
