server:
  port: 10001
spring:
  profiles: base
  application:
    name: turbine-server
turbine:
  aggregator:
    clusterConfig: REGISTER-CENTER
  appConfig: LEARN-SERVICE, TEST-SERVER
  combine-host-port: true
  clusterNameExpression: "'REGISTER-CENTER'"
